site_name: {{cookiecutter.project_name}} Docs

repo_url: https://github.com/{{cookiecutter.github_username}}/{{cookiecutter.project_slug}}

theme: material

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
